dist: trusty
language: node_js
node_js:
  - "8.11.4"
cache: yarn
github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
jobs:
  include:
    - stage: Build
      name: 'Build'
      install:
        - yarn
      script: 'yarn build'
    - stage: Deploy
      name: 'Deploy'
      script: yarn deploy
notifications:
  email:
    - false
